package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserExtendedAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserExtendedAllPropertiesEquals(UserExtended expected, UserExtended actual) {
        assertUserExtendedAutoGeneratedPropertiesEquals(expected, actual);
        assertUserExtendedAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserExtendedAllUpdatablePropertiesEquals(UserExtended expected, UserExtended actual) {
        assertUserExtendedUpdatableFieldsEquals(expected, actual);
        assertUserExtendedUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserExtendedAutoGeneratedPropertiesEquals(UserExtended expected, UserExtended actual) {
        assertThat(expected)
            .as("Verify UserExtended auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserExtendedUpdatableFieldsEquals(UserExtended expected, UserExtended actual) {}

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserExtendedUpdatableRelationshipsEquals(UserExtended expected, UserExtended actual) {
        assertThat(expected)
            .as("Verify UserExtended relationships")
            .satisfies(e -> assertThat(e.getUsers()).as("check users").isEqualTo(actual.getUsers()))
            .satisfies(e -> assertThat(e.getFollows()).as("check follows").isEqualTo(actual.getFollows()));
    }
}
